# Generated by Django 4.0.6 on 2022-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customize'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='reference_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
