# Generated by Django 4.0.6 on 2022-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_estimate_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimatedate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='expirationdate',
            field=models.DateField(),
        ),
    ]
