# Generated by Django 4.0.6 on 2022-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_estimate_estimatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimatedate',
            field=models.DateField(),
        ),
    ]
