# Generated by Django 4.0.6 on 2022-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_estimate_estimatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
