# Generated by Django 4.0.6 on 2022-09-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_estimate_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='CGST',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='IGST',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='SGST',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='TCS',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
