# Generated by Django 4.0.6 on 2022-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_estimate_cgst_estimate_igst_estimate_sgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='CGST',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='IGST',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='SGST',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='TCS',
            field=models.CharField(max_length=100),
        ),
    ]
