# Generated by Django 4.0.6 on 2022-09-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_estimate_cgst_alter_estimate_igst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Invoice', 'Invoice')], default='Draft', max_length=150),
        ),
    ]
