# Generated by Django 4.0.6 on 2022-09-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_estimate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='file',
            field=models.FileField(default=1, upload_to='estimate'),
            preserve_default=False,
        ),
    ]
