# Generated by Django 4.0.6 on 2022-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_salesorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='estimatetotal',
            new_name='salestotal',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='shipmentdate',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
