# Generated by Django 4.0.6 on 2022-09-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_estimatetotal_salesorder_salestotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='saledate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='shipmentdate',
            field=models.DateField(),
        ),
    ]
