# Generated by Django 4.0.6 on 2022-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_salesorder_saledate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Invoice', 'Invoice')], default='Draft', max_length=150),
        ),
    ]
