# Generated by Django 4.0.6 on 2022-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='file',
            field=models.FileField(upload_to='sales'),
        ),
    ]
