# Generated by Django 4.0.6 on 2022-09-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_salesorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='unittable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_symbol', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='mjournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('mj_no', models.CharField(max_length=100)),
                ('ref_no', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('j_type', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(max_length=100)),
                ('account1', models.CharField(max_length=100)),
                ('desc1', models.CharField(max_length=100, null=True)),
                ('contact1', models.CharField(max_length=100, null=True)),
                ('debit1', models.CharField(max_length=100)),
                ('credit1', models.CharField(max_length=100)),
                ('account2', models.CharField(max_length=100)),
                ('desc2', models.CharField(max_length=100, null=True)),
                ('contact2', models.CharField(max_length=100, null=True)),
                ('debit2', models.CharField(max_length=100)),
                ('credit2', models.CharField(max_length=100)),
                ('attach', models.FileField(upload_to='')),
                ('s_totaldeb', models.CharField(max_length=100)),
                ('s_totalcre', models.CharField(max_length=100)),
                ('total_deb', models.CharField(max_length=100)),
                ('total_cre', models.CharField(max_length=100)),
                ('difference', models.CharField(max_length=100)),
                ('status', models.CharField(default='DRAFT', max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='itemtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('tax_reference', models.CharField(max_length=100)),
                ('purchase_cost', models.CharField(max_length=100)),
                ('sales_cost', models.CharField(max_length=100)),
                ('tax_rate', models.CharField(max_length=100)),
                ('acount_pur', models.CharField(max_length=100)),
                ('account_sal', models.CharField(max_length=100)),
                ('pur_desc', models.CharField(max_length=100)),
                ('sale_desc', models.CharField(max_length=100)),
                ('intra_st', models.CharField(max_length=100)),
                ('inter_st', models.CharField(max_length=100)),
                ('inventry', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='currencies',
            fields=[
                ('currencyid', models.AutoField(primary_key=True, serialize=False, verbose_name='CURRENCYID')),
                ('code', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('symbol', models.CharField(blank=True, default='', max_length=255)),
                ('decimal_places', models.CharField(blank=True, default='', max_length=255)),
                ('format', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
