# Generated by Django 4.1 on 2022-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_unittable_mjournal_itemtable_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjournal',
            name='account1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='account2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='attach',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='credit1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='credit2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='currency',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='debit1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='debit2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='difference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='mj_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='ref_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='s_totalcre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='s_totaldeb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='total_cre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='total_deb',
            field=models.CharField(default='', max_length=100),
        ),
    ]
