# Generated by Django 4.1 on 2022-09-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_mjournal_account1_alter_mjournal_account2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjournal',
            name='account1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mjournal',
            name='account2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
