# Generated by Django 4.0.5 on 2022-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_purchasebill_purchaseorder_vendor_porder_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='file',
            field=models.FileField(default=None, upload_to='bill'),
        ),
    ]
