# Generated by Django 4.0.5 on 2022-09-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_purchasebill_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balfordisp',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='detype',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='proid',
        ),
    ]
