# Generated by Django 4.0.6 on 2022-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_remove_accounts_balfordisp_remove_accounts_detype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_orderno',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Invoiced', 'Invoiced')], default='Draft', max_length=150),
        ),
    ]
