# Generated by Django 4.0.6 on 2022-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_invoice_invoice_orderno_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='CGST',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='IGST',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='SGST',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='TCS',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
