# Generated by Django 4.0.6 on 2022-10-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_invoice_cgst_invoice_igst_invoice_sgst_invoice_tcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(default=1, upload_to='invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
