# Generated by Django 4.1 on 2022-10-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_invoice_file_invoice_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='taxamount',
        ),
    ]
