# Generated by Django 4.0.5 on 2022-10-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_purchasebill_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='deftaxcode',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='gst',
        ),
    ]
