# Generated by Django 4.0.5 on 2022-10-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_remove_accounts_deftaxcode_remove_accounts_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='grand_total',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
