# Generated by Django 4.0.5 on 2022-10-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_purchasebill_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts1',
            name='dbbalance',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
