# Generated by Django 4.0.5 on 2022-10-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_accounts1_dbbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts1',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
